mutation addMeal($input: AddMealInput!) {
  addMeal(input: $input) {
    id
    servings
    order
    ingredients {
      id
      amount
      measure
      food {
        id
        portions {
          measure
          gramWeight
        }
      }
    }
  }
}
