import Head from "next/head";
import Link from "next/link";
import ClientOnly from "../components/ClientOnly";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ClientOnly className="flex flex-col space-y-6">
        <h1>Welcome to Nutriplan</h1>
        <Link href="/graphql-test/heroku">
          <a className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 w-28 ml-8">
            Heroku Test
          </a>
        </Link>
        <Link href="/search-test">
          <a className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 w-28 ml-8">
            Search Test
          </a>
        </Link>
      </ClientOnly>
    </div>
  );
}
