import Head from "next/head";
import ClientOnly from "../../../components/ClientOnly";
import RequireAuth from "../../../components/RequireAuth";
import PlanEditor from "../../../components/Plans/PlanEditor";

export default function Home() {
  return (
    <RequireAuth>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ClientOnly>
          <p>Plan page!</p>
        </ClientOnly>
      </div>
    </RequireAuth>
  );
}
