import { useEffect } from "react";
import { addDays } from "date-fns";
import { useRouter } from "next/router";
import Head from "next/head";
import ClientOnly from "../../components/ClientOnly";
import RequireAuth from "../../components/RequireAuth";
import { useCreatePlanMutation } from "../../generated/graphql";

export default function NewPlan() {
  const [createPlan, { loading, error }] = useCreatePlanMutation({
    variables: { input: { name: "New plan", startDate: new Date(), endDate: addDays(new Date(), 7) } },
  });
  const router = useRouter();
  useEffect(() => {
    const createPlanAndRedirect = async () => {
      const result = await createPlan();
      if (result.data?.createPlan?.id) {
        void router.push(`/plans/${result.data.createPlan.id}/edit`);
      } else {
        // TODO: figure out error handling here
        console.error(result);
      }
    };
    void createPlanAndRedirect();
  }, [createPlan, router]);

  if (loading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }
  return (
    <RequireAuth>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ClientOnly>
          <h1>Creating new plan...</h1>
        </ClientOnly>
      </div>
    </RequireAuth>
  );
}
