import Head from "next/head";
import Link from "next/link";
import ClientOnly from "../components/ClientOnly";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ClientOnly>
        <h1>Welcome to Nutriplan</h1>
        <Link href="/graphql-test/heroku">
          <a>Heroku Test</a>
        </Link>
      </ClientOnly>
    </div>
  );
}
