query getPlanWithNutrients($planId: Int!) {
  plan(id: $planId) {
    id
    startDate
    endDate
    name
    ingredients {
      id
      amount
      measure
      order
      food {
        id
        description
        portions {
          measure
          gramWeight
        }
        foodNutrients {
          id
          amount
          nutrient {
            id
            name
            unit
          }
        }
      }
    }
    meals {
      id
      servings
      order
      recipe {
        name
        id
      }
      ingredients {
        id
        amount
        measure
        order
        food {
          id
          description
          portions {
            measure
            gramWeight
          }
          foodNutrients {
            id
            amount
            nutrient {
              id
              name
              unit
            }
          }
        }
      }
    }
  }
}
