# TODO: Add optional nutrientIds param to avoid sending all nutrients
query getFoodsWithNutrients($foodIds: [Int!]!) {
  foods(ids: $foodIds) {
    id
    nutrients {
      id
      amount
      name
      unit
    }
  }
}
