# TODO: Add optional nutrientIds param to avoid sending all nutrients
query getFoodsWithNutrients($foodIds: [Int!]!) {
  foods(ids: $foodIds) {
    id
    description
    foodNutrients {
      id
      amount
      nutrient {
        id
        name
        unit
      }
    }
  }
}
