query SearchFoods($searchTerm: String!) {
  searchFoods(searchTerm: $searchTerm) {
    description
    id
    dataSource
    category
    brandName
    searchScore
    portions {
      measure
      gramWeight
    }
  }
}
