query SearchFoods($searchTerm: String!) {
  searchFoods(searchTerm: $searchTerm) {
    description
    id
    data_source
    category
    brand
    serving_size
    searchScore
    ingredients
    portions {
      id
      measure
      gram_weight
      sequence_number
    }
    food_nutrients {
      id
      amount
      nutrient {
        name
      }
    }
  }
}
